def copy(nums:list[int]) -> list[int]:
    new_list = []
    for idx in range(len(nums)):
        new_list.append(nums[idx])     #idx:0,new_list:[4] #idx:1,new_list:[4,9] #idx:2,new_list:[4,9,2] #idx:3,new_list:[4,9,2,1]
    return new_list                    # This loop uses the position generated by the idx to find the num
                                    # while the other loop uses different variables to evaluate what num is

result = copy([4, 9, 2, 1])